language: rust

dist: trusty
sudo: false

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  - TARGET=asmjs-unknown-emscripten
  - TARGET=wasm32-unknown-emscripten
  - TARGET=wasm32-unknown-unknown

script:
  - nvm install 9
  - ./ci.sh
